services:
  postgres-db:
    image: postgres:16
    container_name: postgresku
    restart: always
    environment:
      PGTZ: "Asia/Jakarta"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./docker/postgres-16:/var/lib/postgresql/data
    networks:
      - local_network

networks:
  local_network:
    name: local_network
    driver: bridge
